src/YouSurvey/Controllers/SurveyCreatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YouSurvey.Data;
using YouSurvey.Models;

namespace YouSurvey.Controllers
{
    [Authorize]
    public class SurveyCreatorController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public SurveyCreatorController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Gets list of all surveys created by the current user
        /// </summary>
        /// <returns></returns>
        public IActionResult List()
        {
            var currentUser = HttpContext.User;
            return Ok(_dbContext.Surveys.Where(survey => survey.CreatedBy == currentUser.Identity.Name));
        }

        /// <summary>
        /// Gets the view to enable creating a new survey
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates a new survey
        /// </summary>
        /// <param name="survey"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create(Survey survey)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            // add survey to store

            return RedirectToAction("Details");
        }

        /// <summary>
        /// Gets the view showing details of a survey and its questions.
        /// Provides links to create choices for the survey
        /// </summary>
        /// <returns></returns>
        public IActionResult Details(int id)
        {
            return View();
        }

        /// <summary>
        /// Gets the view to enable creating a new question and choices
        /// </summary>
        /// <returns></returns>
        public IActionResult CreateQuestion()
        {
            return View();
        }

        /// <summary>
        /// Creates a question
        /// </summary>
        /// <param name="question"></param>
        /// <returns></returns>
        public IActionResult CreateQuestion(Question question)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            // add question to a survey
            // update survey to store

            return RedirectToAction("Details");
        }

        /// <summary>
        /// Shows the details of a question
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult QuestionDetails(int id)
        {
            return View();
        }

        /// <summary>
        /// Indicates completion of survey creation.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Completed(int id)
        {
            // save the surveys to the completed list of surveys

            return RedirectToAction("Index");
        }
    }
}

src/YouSurvey/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YouSurvey</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">YouSurvey</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Surveys <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="SurveyCreator" asp-action="Create">Create</a></li>
                            <li><a asp-controller="SurveyCreator" asp-action="Index">Manage</a></li>
                        </ul>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - YouSurvey</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/angular/angular.min.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/models.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"
            asp-fallback-src="~/lib/angular/angular.min.js">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>